name: Latest Release Build
on:
  release:
    types:
      - released
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: 'recursive'
      - uses: c-hive/gha-yarn-cache@v1
      - name: Install modules
        run: yarn
      - name: Build extensions
        run: |
          VERSION=$(echo -n ${{ github.ref }} | sed 's/[refs\/tagv]//g') yarn build
          yarn package
      - name: Upload Chrome package to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/HyperChat-Chrome.zip
          asset_name: HyperChat-Chrome.zip
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload Firefox package to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/HyperChat-Firefox.zip
          asset_name: HyperChat-Firefox.zip
          tag: ${{ github.ref }}
          overwrite: true
