name: Latest Release Build
on:
  release:
    types:
      - released
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: 'recursive'
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Package extensions
        run: |
          npm install
          npm run build 
          node utils/package.js --version=$(echo -n ${{ github.ref }} | sed 's/[refs\/tagv]//g')
      - name: Upload Chrome package to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: zips/HyperChat-Chrome.zip
          asset_name: HyperChat-Chrome.zip
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload Firefox package to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: zips/HyperChat-Firefox.zip
          asset_name: HyperChat-Firefox.zip
          tag: ${{ github.ref }}
          overwrite: true
